const { setup } = require('../support/setup')
const { waitForActive } = require('../support/commands')

describe('Main', () => {
  beforeEach(() => setup())

  it('can view items', () => {
    cy.get('tbody tr').should('have.length', 20)
  })
  it('can create item', () => {
    cy.get('tbody tr').should('have.length', 20)
    cy.contains('button', 'New Item').click()
    waitForActive('input')
    cy.focused()
      .type('Mr mole')
      .tab()
      .type('asdf')
      .tab()
      .type('asdf')
      .tab()
      .type('foobar123')
    cy.get('[data-test="edit-image"]').click()
    waitForActive('[data-test="imageUrl"]')
    cy.focused()
      .type(
        '{selectall}{del}https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2Fimages3.wikia.nocookie.net%2F__cb20120830122040%2Fscratchpad%2Fimages%2F3%2F36%2FJamjarsBanjoTooie.png&f=1',
      )
      .type('{enter}')
  })
  it('can delete', () => {
    cy.get('tbody tr')
      .should('have.length', 20)
      .should('contain', 'Concrete Pizza')
    cy.get('[data-test="delete"]')
      .eq(2)
      .click()
    cy.get('tbody tr')
      .should('have.length', 19)
      .should('not.contain', 'Concrete Pizza')
  })
  it('can update', () => {
    cy.get('[data-test="edit"]')
      .eq(2)
      .click()
    cy.tab()
      .tab()
      .type('NEW VALUE')
      .tab()
      .tab()
      .tab()
      .type('123456{enter}')
    cy.get('tbody tr')
      .should('have.length', 20)
      .should('not.contain', 'Concrete Pizza')
      .should('contain', 'NEW VALUE')
  })
})
